### ISSUE TITLE
Support for Windows - Latest in Visual Studio

### ISSUE THREAD

**Issue by GaryDeco** [krpc/krpc2#1]
- [x] Update .csproj .dll references to work with windows.

**Comment by djungelorm** [comment]
Worked fine for me on Visual Studio 2022.

Did you find a problem?

**Comment by GaryDeco** [comment]
The references do not work out the box. At least for windows. I realize that you can just copy over dlls. By adding a conditional reference to check in default  game location it is more build and go. Unless we add .bat/.sh to copy them over. Seemed the reference change would have lower cost.

**Comment by djungelorm** [comment]
Right. It was just a quick first attempt to get something functional.

Let's leave it as is for now. Once the Windows build scripts for krpc1 are more finalized, we can use the same for this repo.

**Comment by djungelorm** [comment]
I've updated the repository to use Bazel as its build system. It uses the new (to me) `rules_dotnet`. So it works on Windows and Linux :) The ksp libraries still need to be manually copied into `lib/ksp2`.

I've also added a KRPC2.csproj file that should also work with Visual Studio. However, you do first need to run bazel to fetch dependencies.

**Comment by djungelorm** [comment]
Note: I am working on this as part of the project restructure.

The approach will be to copy the KSP2 DLL to `lib/ksp` then build using the .csproj or .sln files. I think this is the simplest cross-platform way to do it.
