### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by GaryDeco** [krpc/krpc2#31]
Add Issue templates mirroring those added to krpc to maintain organization.

**Comment by dmadisetti** [comment]
Hmm, clicking create issue doesn't seem to trigger the template

**Comment by djungelorm** [comment]
Same here.

**Comment by GaryDeco** [comment]
> Hmm, clicking create issue doesn't seem to trigger the template

You are right! I just looked through docs and from what I can see and what we did in krpc, it should work.

**Comment by dmadisetti** [comment]
I think it might need to be enabled on the repository level:
https://github.com/krpc/krpc2/issues/templates/edit
