### ISSUE TITLE
Change build system so you don't need to copy large files

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc2#4]
The `Kerbal Space Program 2/KSP2_x64_Data` directory is ~33GB. Currently the build system requires you _copy_ this directory to `lib/ksp2/KSP2_x64_Data/...` in order to build the project. This is unreasonable -- what if you don't have much disk space? (On Linux this is less of an issue as you can use a symlink, more of a problem on Windows)

We should change this to require `Kerbal Space Program 2/KSP2_x64_Data/Managed` directory to be copied to `lib/ksp2/Managed/...`. This is only ~50MB

@GaryDeco sound good to you?

**Comment by GaryDeco** [comment]
100%. That is how I was doing it on my end. I was having a .bat file copy the KSP_x64_Data/managed folder and renaming it to match your configuration. You could go as far as copying over required dlls only.

**Comment by djungelorm** [comment]
Yeah that would also work and is probably tidier. Ctrl-C all the files in `KSP_x64_Data/Managed` and paste them into `lib/ksp2`.

We could use the same scheme for krpc1 as well (this would completely side step the issue there that it is `KSP_x64_Data` on Windows and `KSP_Data` on Linux...)

I've almost finished some major changes to the build system, and will include this change with that. (My changes will establish the krpc-core repository, and set this one up to depend on it, rather than using a pre-built KRPC.Core.dll as it does currently)

**Comment by djungelorm** [comment]
Yes you could do that. This scheme doesn't preclude that. You can copy/link the DLLs however you like (advantage of not using a script - you can choose how you want to do it)

**Comment by djungelorm** [comment]
I've remembered why I had it set up like this. It's so that scripts like `tools/run-ksp.sh` would work. That requires a full copy of KSP in the directory.

So let's leave it as is. As @BenChung points out, you could just use a link on Windows.
