### ISSUE TITLE
Basic orbital parameters

### ISSUE THREAD

**Issue by djungelorm** [krpc/krpc2#9]
Implement basic orbital parameters in `SpaceCenter.Orbit` for vessels.

See https://github.com/krpc/krpc/blob/main/service/SpaceCenter/src/Services/Orbit.cs

 - [ ] Constructor from a Vessel object
 - [ ] Orbit.Apoapsis
 - [ ] Orbit.Periapsis
 - [ ] Orbit.ApoapsisAltitude
 - [ ] Orbit.PeriapsisAltitude
 - [ ] Orbit.SemiMajorAxis
 - [ ] Orbit.SemiMinorAxis
 - [ ] Orbit.Radius

**Comment by GaryDeco** [comment]
I like that. Should we add milestones? Or maybe a version milestone?

**Comment by djungelorm** [comment]
Yeah good idea. Version milestone like we do for krpc1
